services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-zisk
      POSTGRES_DB: op-zisk
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  op-zisk:
    build:
      context: .
      dockerfile: ./validity/Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - DATABASE_URL=postgres://op-zisk@postgres:5432/op-zisk
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
